# Generated by Django 4.1.2 on 2022-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=150, null=True)),
                ('volume24h', models.CharField(blank=True, max_length=150, null=True)),
                ('one_hour_per', models.CharField(blank=True, max_length=150, null=True)),
                ('one_day_per', models.CharField(blank=True, max_length=150, null=True)),
                ('seven_day_per', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
