# Generated by Django 4.1.2 on 2022-10-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address_Details',
            new_name='Coin_Market',
        ),
        migrations.AlterModelOptions(
            name='coin_market',
            options={'ordering': ['-created_at']},
        ),
    ]
