# Generated by Django 4.1.2 on 2022-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_coin_market_row_number_coin_market_coin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_market',
            name='circulating_supply',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
